apiVersion: skaffold/v2beta1
kind: Config
build:
  local: {}
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: mingerz/hello-kubernetes
deploy:
  kubectl:
    manifests:
      - yaml/hello-kubernetes.custom-message.yaml
